metadata:
  name: "Disallow open ingress to 0.0.0.0/0"
  id: "MASA_TF_NET_001"
  category: "Networking"
  severity: "HIGH"
scope:
  provider: "terraform"
definition:
  and:
    - resource_types:
        - aws_security_group_rule
    - attribute: cidr_blocks
      condition: contains
      value: "0.0.0.0/0"
    - attribute: type
      condition: equals
      value: "ingress"
