metadata:
  id: "COMPANY_HELM_004"
  name: "Network Policy Required"
  category: "NETWORKING"
  severity: "MEDIUM"
  description: "All deployments must have an associated NetworkPolicy"
  guideline: "Company Networking Policy CNP-004"
definition:
  cond_type: "filter"
  resource_types:
    - "helm_template"
  attribute: "kind"
  operator: "equals"
  value: "Deployment"
  filter_eval: "any"
  filter:
    - cond_type: "exists"
      resource_types:
        - "NetworkPolicy"
      attribute: "metadata.labels.app"
      value_from:
        resource_type: "Deployment"
        attribute: "metadata.labels.app"
  remediation: |
    Create a NetworkPolicy that targets this deployment using app labels.
    Example:
    kind: NetworkPolicy
    metadata:
      name: allow-app
    spec:
      podSelector:
        matchLabels:
          app: {{ app-label }}
