metadata:
  id: "COMPANY_HELM_002"
  name: "Resource Limits Required"
  category: "GOVERNANCE"
  severity: "MEDIUM"
  description: "All containers must have CPU and memory limits defined"
  guideline: "Company Resource Policy CRP-002"
definition:
  cond_type: "combined"
  resource_types:
    - "helm_template"
  and:
    - attribute: "spec.containers[].resources.limits.cpu"
      operator: "exists"
    - attribute: "spec.containers[].resources.limits.memory"
      operator: "exists"
  remediation: |
    Add resource limits to all containers:
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
